apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 6969
      protocol: TCP
      targetPort: 6969

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 626557673667.dkr.ecr.ap-southeast-1.amazonaws.com/ecr-nashtech-devops-backend:$tagbe
          imagePullPolicy: Always
          ports:
            - containerPort: 6969