---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongo-sc
provisioner: kubernetes.io/no-provisioner
# provisioner: kubernetes.io/aws-ebs
# parameters:
#   type: gp3
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  selector:
    name: mongo
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  MONGODB_INITDB_ROOT_USERNAME: "user"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
type: Opaque
data:
  MONGODB_INITDB_ROOT_PASSWORD: cGFzc3dvcmQK

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  storageClassName: mongo-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      name: mongo
  serviceName: "mongo"
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo
        ports:
          - containerPort: 27017
        envFrom:
         - configMapRef:             
               name: mongo-config
         - secretRef:
             name: mongo-secrets
        volumeMounts:
            - name: data-volume
              mountPath: /data/db
        resources:
          requests:
            cpu: 0.2
            memory: 200Mi
  volumeClaimTemplates:
    - metadata:
        name: data-volume
      spec:
        storageClassName: mongo-sc
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Gi"


