apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    {{- include "app.label" . | nindent 4 }}
  ports:
    - port: {{ .Values.servicePort }}
      protocol: TCP
      targetPort: {{ .Values.servicePort }}
      name: be-tcp

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-bluegreen-preview
spec:
  selector:
    {{- include "app.label" . | nindent 4 }}
  ports:
    - port: {{ .Values.servicePort }}
      protocol: TCP
      targetPort: {{ .Values.servicePort }}
      name: be-tcp