apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-grantor
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

--- 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-enforce
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-grantor-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: role-grantor
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  namespace: kube-system
  name: arn:aws:iam::626557673667:role/bastion-nashtech-devops
