# Replica count for the backend deployment
replicaCount: 1

# name of resources such as deployment, container, service
name: backend

# Image repository and tag for the backend container
image:
  repository: dungacr.azurecr.io/devops-backend
  tag: latest

# Port for the backend service
servicePort: 3000