apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "app.label" . | nindent 4 }}
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "app.label" . | nindent 6 }}
  strategy:
    blueGreen:
      autoPromotionEnabled: false
      activeService: {{ .Values.name }}
      previewService: {{ .Values.name }}-bluegreen-preview
  template:
    metadata:
      labels:
        {{- include "app.label" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.servicePort }}
              protocol: TCP