apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    {{- include "app.label" . | nindent 4 }}
  ports:
    - port: {{ .Values.servicePort }}
      protocol: TCP
      targetPort: {{ .Values.servicePort }}
      name: fe-tcp
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-bluegreen-preview
spec:
  selector:
    {{- include "app.label" . | nindent 4 }}
  ports:
    - port: {{ .Values.servicePort }}
      protocol: TCP
      targetPort: {{ .Values.servicePort }}
      name: fe-tcp
  type: ClusterIP